services:
  - type: web
    name: mi-backend-aternos
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libxml2-dev libxslt-dev python3-dev
      pip install -r requirements.txt
    startCommand: python app.py