services:
  - type: web
    name: dweller-aternos
    env: python
    pythonVersion: 3.11.9
    buildCommand: |
      apt-get update && apt-get install -y libxml2-dev libxslt-dev python3-dev
      pip install -r requirements.txt
    startCommand: python app.py
